# config.py
import os
from dotenv import load_dotenv

load_dotenv()

# --- Credentials ---
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
# gmail passcode generated by gmail /Google 
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD") 
GMAIL_ACCOUNT_NAME = os.getenv("GMAIL_ACCOUNT_NAME")

# --- File Paths ---
RESUME_PATH = "PANKAJ_SHAHARE_RESUME.pdf"
RECIPIENTS_FILE = "recipients.xlsx"
LOG_FILE = "email_log.csv"
SUBJECT_FILE = "email_subject.txt"
BODY_FILE = "email_body.html"
